"""empty message

Revision ID: 1f799a53e1d2
Revises: e280290c16b9
Create Date: 2024-01-17 11:20:00.987021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f799a53e1d2'
down_revision = 'e280290c16b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('youtube_link', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('info_hospital', sa.Text(), nullable=True))
        batch_op.drop_column('search_keywords')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_keywords', sa.TEXT(), nullable=True))
        batch_op.drop_column('info_hospital')
        batch_op.drop_column('youtube_link')

    # ### end Alembic commands ###
