"""added new columns

Revision ID: 34b33a399813
Revises: 724aa1cd414c
Create Date: 2023-12-13 05:08:44.778314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34b33a399813'
down_revision = '724aa1cd414c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bloodgroup', sa.Enum('a_positive', 'b_positive', 'ab_positive', 'o_positive', 'a_negative', 'b_negative', 'ab_negative', 'o_negative', name='bloodgroup'), nullable=True))
        batch_op.add_column(sa.Column('genotype', sa.Enum('AA', 'AS', 'SS', 'SC', 'AC', name='genotype'), nullable=True))
        batch_op.add_column(sa.Column('medical_history', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('medical_history')
        batch_op.drop_column('genotype')
        batch_op.drop_column('bloodgroup')

    # ### end Alembic commands ###
