"""added search keywords

Revision ID: 76b0efe51f10
Revises: 34b33a399813
Create Date: 2023-12-27 20:49:44.452302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76b0efe51f10'
down_revision = '34b33a399813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_dict_done', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('search_keywords', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_column('search_keywords')
        batch_op.drop_column('is_dict_done')

    # ### end Alembic commands ###
