"""empty message

Revision ID: e280290c16b9
Revises: bbd6e4e9d3e8
Create Date: 2024-01-12 18:20:45.026185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e280290c16b9'
down_revision = 'bbd6e4e9d3e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anonyuser', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.alter_column('anony_user_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.alter_column('anony_user_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)

    with op.batch_alter_table('anonyuser', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###
